### ISSUE TITLE
new Unity ObjectPool API

### ISSUE THREAD

**Issue by enkeyz** [ertanturan/Unity-Object-Pooling#4]
Do you think writing your own objectpool still relevant, after Unity added an offical API 2021.1 and later versions?

https://docs.unity3d.com/2021.1/Documentation/ScriptReference/Pool.ObjectPool_1.html

**Comment by ertanturan** [comment]
Yes it's relevant. Because, you may need to change something in behaviour of the object pool ,  adding injection, editing the interface, making it extendable and shrinkable ?. But I got your point. If Unity's pool fits your requirements than it's not relevant.
